apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment

spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
        